#pragma once

#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 175
#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD

#define VIAL_UNLOCK_COMBO_ROWS { 1, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 11 }
#define VIAL_KEYBOARD_UID {0x22, 0x89, 0x7B, 0x2E, 0xA4, 0xA3, 0x1D, 0x9B}